### ISSUE TITLE
Robbery spam console

### ISSUE THREAD

**Issue by donnayy** [TanguyOrtegat/esx_holdupbank#4]
When someone leave the bank while the robbey is in progress 
the server console spams error messages.
Do you know what can be?

 [C]: in function 'error'
        citizen:/scripting/lua/scheduler.lua:41: in field 'CreateThreadNow'
        citizen:/scripting/lua/scheduler.lua:218: in function <citizen:/scripting/lua/scheduler.lua:182>
Error running system event handling function for resource esx_holdupbank: citizen:/scripting/lua/scheduler.lua:41: Failed to execute thread: server/server.lua:21: attempt to index a nil value (global 'banks')

**Comment by TanguyOrtegat** [comment]
at line 21 there is no word banks, so you don't have the correct script
